# milvus_store.py
import json
import logging
from pymilvus import MilvusClient, DataType, Function, FunctionType
from pymilvus.orm.schema import FieldSchema, CollectionSchema
from sentence_transformers import SentenceTransformer
from .md_splitter import Chunk

logger = logging.getLogger(__name__)

COLLECTION_NAME = "knowledge_base"
_dense_model = None


def _get_dense_model() -> SentenceTransformer:
    global _dense_model
    if _dense_model is None:
        from ...config.settings import get_settings
        s = get_settings()
        _dense_model = SentenceTransformer(s.embedding_model, device=s.embedding_device)
    return _dense_model


def _get_dense_dim() -> int:
    from ...config.settings import get_settings
    return get_settings().embedding_dimension


def init_collection(client: MilvusClient) -> None:
    if client.has_collection(COLLECTION_NAME):
        client.load_collection(COLLECTION_NAME)
        logger.info("collection %s already exists, loading", COLLECTION_NAME)
        return

    dim = _get_dense_dim()
    analyzer_params = {"type": "standard"}

    fields = [
        FieldSchema("id", DataType.INT64, is_primary=True, auto_id=True),
        FieldSchema("dense_vec", DataType.FLOAT_VECTOR, dim=dim),
        FieldSchema("sparse_vec", DataType.SPARSE_FLOAT_VECTOR),
        FieldSchema("content", DataType.VARCHAR, max_length=65535,
                    analyzer_params=analyzer_params, enable_match=True, enable_analyzer=True),
        FieldSchema("chunk_type", DataType.VARCHAR, max_length=32),
        FieldSchema("meta_json", DataType.VARCHAR, max_length=65535),
        FieldSchema("doc_source", DataType.VARCHAR, max_length=512),
        FieldSchema("parent_title_key", DataType.VARCHAR, max_length=300),
    ]
    schema = CollectionSchema(fields, description="RAG collection for md documents",
                              enable_dynamic_field=True)

    # server-side BM25: content text -> sparse_vec (auto on every insert)
    bm25_func = Function(
        name="content_bm25",
        input_field_names=["content"],
        output_field_names=["sparse_vec"],
        function_type=FunctionType.BM25,
    )
    schema.add_function(bm25_func)

    client.create_collection(collection_name=COLLECTION_NAME, schema=schema)

    index_params = client.prepare_index_params()
    index_params.add_index(field_name="dense_vec", index_type="IVF_FLAT", metric_type="L2",
                           params={"nlist": 128})
    index_params.add_index(field_name="sparse_vec", index_type="SPARSE_INVERTED_INDEX",
                           metric_type="BM25")
    client.create_index(collection_name=COLLECTION_NAME, index_params=index_params)
    client.load_collection(COLLECTION_NAME)
    logger.info("collection %s created successfully", COLLECTION_NAME)


def insert_chunks(client: MilvusClient, chunk_list: list[Chunk], source_file_name: str):
    rows = []
    for ck in chunk_list:
        d_vec = _get_dense_model().encode(ck.content).tolist()
        rows.append({
            # id auto-generated by Milvus (INT64 auto_id=True)
            "dense_vec": d_vec,
            "content": ck.content,
            "chunk_type": ck.chunk_type,
            "meta_json": json.dumps(ck.metadata, ensure_ascii=False),
            "doc_source": source_file_name,
            "parent_title_key": ck.metadata["parent_title_key"],
        })
    client.insert(collection_name=COLLECTION_NAME, data=rows)
    client.flush(collection_name=COLLECTION_NAME)
    logger.info("insert complete: %d chunks from %s", len(chunk_list), source_file_name)


def md_to_milvus(client: MilvusClient, md_text: str, src_name: str, splitter):
    chunks = splitter.split_text(md_text)
    insert_chunks(client, chunks, src_name)
    return chunks
